import './globals.css';
import type { Metadata } from 'next';
import { Inter, Lora, Spectral } from 'next/font/google';
import { ThemeProvider } from './theme-provider';
import Footer from './footer';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';
import TopNav from '@/components/Global/TopNav';

const inter = Inter({ subsets: ['latin'] });
const lora = Lora({ subsets: ['latin'] });
const spectral = Spectral({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={spectral.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <main>
            <TopNav />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
